# Generated by Django 5.0.6 on 2024-06-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('out-for-delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='booked', max_length=20),
        ),
    ]
